### ISSUE TITLE
Focusdag 1: Wat is SOLID?

### ISSUE THREAD

**Issue by marcvanandel** [marcvanandel/solid-quest#1]
Vragen voor focusdag 1:

- Is een SOLID pod alleen data opslag?
- Is het toevoegen van een specifieke context door het uitvoeren van een app die gebruik maakt van een SOLID pod?
- Of is het mogelijk om een bepaalde semantisch dialect toe te voegen aan een SOLID pod?
- Hoe ontwikkel je een 'SOLID app'?

Te onderzoeken voorbeelden:
- Een uit chat app uit [SOLID socials](https://solidproject.org/apps#social)
  - decentrale chat opslag?
  - wat is de gezamenlijke chat dan?
- [Diagram](https://arquisoft.github.io/dede_en2a/#_level_3) uit de 21/22 challenge van 'uni van or... nog wat'

**Comment by marcvanandel** [comment]
Diving into [WebID](https://en.wikipedia.org/wiki/WebID) I come to the realization that a WebID is multiple things. It is a document describing an entity, mostly a person ... but it could be an organization or service (bot) as well. It also covers authentication and authorization. This is based on the general open standers of OpenID Connect / OAuth2 (and extends this for some reason and is called WebID-OIDC 🙈 ).

So with a WebID you can authenticate yourself _and_ describe yourself with your profile. This combination is a strong proposition ... but also confuses (me at least)

**Comment by marcvanandel** [comment]
(playing in my personal space at [marcvanandel.nl](https://marcvanandel.nl] 😁 with a [Linked Data plugin](https://nl.wordpress.org/plugins/wp-linked-data/))

**Comment by marcvanandel** [comment]
![2022-07-20 15 46 18](https://user-images.githubusercontent.com/2315396/179998926-7771aa2b-f149-481a-b221-87f5258f34d8.jpg)

**Comment by marcvanandel** [comment]
Toevoegen in uiteindelijke story dat er in de huidige platformen geen keuze is waar de data opgeslagen wordt; het komt allemaal in de grote database van het platform. Er zijn tegenwoordig al wel meer mogelijkheden om de frontend / user interface te kiezen ... maar vanaf de API is er dan geen keuze (... hoogstens keuze van platform).

Met SOLID pods draait hier echt wezenlijk iets om. Ja, je kunt nog steeds kiezen welke app / frontend / user interface je wilt gebruiken ... maar elke app vraagt eerst naar waar de data opgeslagen moet gaan worden! Eerst besluiten welke online data space de data mag staan en dus wie verantwoordelijk is voor het beheer van die data en daarna komt pas functionaliteit. Dit is echt anders dan de huidige inrichting!

Het helpt voor het verhaal om deze verandering duidelijk te visualiseren.

**Comment by kad-michij** [comment]
Schets nog iets netter uitgewerkt:

![image](https://user-images.githubusercontent.com/62643510/180768425-099521ef-f1b5-4876-8d6b-616fd28236b5.png)

**Comment by kad-michij** [comment]
Wellicht ook goed om nog een plaat/schets te maken van hoe het nu meestal gaat, zodat het verschil duidelijk is?

**Comment by kad-rowla** [comment]
Als een soort van process flow voor applicatie ontwikkeling, hebben we deze plaatje gemaakt: 
![zorgeloos-vastegoed-pods drawio](https://user-images.githubusercontent.com/74549995/182599693-22fb9b41-b1d4-4035-a2c3-ff4ff9453d97.png)

**Comment by marcvanandel** [comment]
Ja, goed idee!

**Comment by marcvanandel** [comment]
Dag 1 was leuk en we hebben veel geleerd ... !!

Deze info is ondertussen bekend en/of vastgelegd in de documentatie ([README.md](https://github.com/marcvanandel/solid-quest/blob/main/README.md)) van deze repo.
