### ISSUE TITLE
Focusdag 3: Sequence diagram verder uitgewerkt

### ISSUE THREAD

**Issue by marcvanandel** [marcvanandel/solid-quest#3]
Op basis van #2 flow diagrammen en vindingen nu een verder detail uitwerking gemaakt in een (huge!) sequence diagram ...

**Comment by marcvanandel** [comment]
Bovenstaande diagram is te wijzigen door dit tekst bestand te laden in [SequenceDiagram.org](https://sequencediagram.org/)

[SolidKoopovereenkomstDemonstrator-1.txt](https://github.com/marcvanandel/solid-quest/files/9363098/SolidKoopovereenkomstDemonstrator-1.txt)

**Comment by marcvanandel** [comment]
In de demo die in #2 genoemd wordt, vind ik de integratie met Solid PODs met name in het aanvragen van autorisaties, nogal onduidelijk voor niet-technische gebruikers. Ik zou daar wel graag een betere user interface voor willen zien ... maar ik weet niet of we dan _ín_ de Solid Community Server iets moeten aanpassen ... 🤔

**Comment by NickvApeldoorn** [comment]
Ik heb 'm verbeterd 😛 
[SolidKoopovereenkomstDemonstrator-1.txt](https://github.com/marcvanandel/solid-quest/files/9373981/SolidKoopovereenkomstDemonstrator-1.txt)

**Comment by marcvanandel** [comment]
Maar deze is nóg beter 😜
[SolidKoopovereenkomstDemonstrator-1.txt](https://github.com/marcvanandel/solid-quest/files/9374942/SolidKoopovereenkomstDemonstrator-1.txt)

('t Wordt tijd om 'm onder versiebeheer te stoppen, denk ik ... 😇  )

**Comment by marcvanandel** [comment]
De laatste versie van het sequence diagram staat als tekstbestand en als plaatje in de repo. Het architectuurplaatje en het sequence diagram gaan nu uit van slechts twee PODs, namelijk die van Verkoper en Koper. Een makelaarPOD zoals eerder voorgesteld, is enigszins tegen het concept van 'user owns all data'.

Alle bovenstaande discussie is opgenomen in de repo documentatie
